"""
Historical Data Pipeline — Mining RTI Demo
===========================================
Automated pipeline that chains historical data generation and ingestion into
Fabric KQL Database as a single operation.

Orchestrates:
  1. generate_history.py — generates CSV files for SensorReadings and SafetyIncidents
  2. ingest_history.py — ingests CSVs into Fabric Eventhouse/KQL Database

Designed for both local development and CI/CD workflows. Supports service principal
authentication, dry-run validation, and selective execution.

Prerequisites:
    pip install azure-identity azure-kusto-data azure-kusto-ingest tqdm

Usage:
    # Generate 30 days of history and ingest
    python deploy_history.py \\
        --cluster https://cluster.kusto.fabric.microsoft.com \\
        --database MiningOps

    # Generate 7 days with custom interval
    python deploy_history.py \\
        --cluster https://cluster.kusto.fabric.microsoft.com \\
        --database MiningOps \\
        --days 7 \\
        --interval 60

    # Dry run (generate data but don't ingest)
    python deploy_history.py \\
        --cluster https://cluster.kusto.fabric.microsoft.com \\
        --database MiningOps \\
        --dry-run

    # Skip generation, ingest existing CSV
    python deploy_history.py \\
        --cluster https://cluster.kusto.fabric.microsoft.com \\
        --database MiningOps \\
        --skip-generate

    # CI/CD mode with service principal
    python deploy_history.py \\
        --cluster https://cluster.kusto.fabric.microsoft.com \\
        --database MiningOps \\
        --tenant-id $AZURE_TENANT_ID \\
        --client-id $AZURE_CLIENT_ID \\
        --client-secret $AZURE_CLIENT_SECRET

Environment Variables (alternative to CLI flags):
    FABRIC_CLUSTER_URI          - Kusto cluster URI
    FABRIC_DATABASE             - KQL database name (default: MiningOps)
    AZURE_TENANT_ID             - Service principal tenant ID
    AZURE_CLIENT_ID             - Service principal client ID
    AZURE_CLIENT_SECRET         - Service principal client secret

Credential Chain (in order of precedence):
    1. CLI arguments (--tenant-id, --client-id, --client-secret)
    2. Environment variables (AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET)
    3. DefaultAzureCredential (Azure CLI, managed identity, etc.)
    4. Interactive browser authentication (fallback)

Exit Codes:
    0  - Success
    1  - Configuration error (missing required args, file not found, etc.)
    2  - Generation failure
    3  - Ingestion failure
    4  - Partial failure (generation succeeded but ingestion failed)
"""

from __future__ import annotations

import argparse
import logging
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("history-pipeline")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
SIMULATOR_DIR = PROJECT_ROOT / "simulator"
ACTIVATOR_DIR = PROJECT_ROOT / "activator"
HISTORY_DATA_DIR = SIMULATOR_DIR / "historical_data"

GENERATE_SCRIPT = SIMULATOR_DIR / "generate_history.py"
INGEST_SCRIPT = ACTIVATOR_DIR / "ingest_history.py"

# CSV files generated by generate_history.py
SENSOR_CSV = HISTORY_DATA_DIR / "SensorReadings.csv"
INCIDENTS_CSV = HISTORY_DATA_DIR / "SafetyIncidents.csv"


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------
def validate_environment() -> None:
    """Validate that required scripts exist."""
    if not GENERATE_SCRIPT.exists():
        log.error("Generation script not found: %s", GENERATE_SCRIPT)
        sys.exit(1)
    
    if not INGEST_SCRIPT.exists():
        log.error("Ingestion script not found: %s", INGEST_SCRIPT)
        sys.exit(1)
    
    log.debug("✓ Scripts found: generate_history.py, ingest_history.py")


def validate_generated_files() -> bool:
    """Check if CSV files exist and have data."""
    if not SENSOR_CSV.exists():
        log.error("SensorReadings.csv not found at: %s", SENSOR_CSV)
        return False
    
    if not INCIDENTS_CSV.exists():
        log.error("SafetyIncidents.csv not found at: %s", INCIDENTS_CSV)
        return False
    
    # Check if files have content (not just headers)
    sensor_size = SENSOR_CSV.stat().st_size
    incidents_size = INCIDENTS_CSV.stat().st_size
    
    if sensor_size < 1024:  # Less than 1KB suggests empty or header-only
        log.error("SensorReadings.csv appears empty (size: %d bytes)", sensor_size)
        return False
    
    log.info("✓ CSV files validated:")
    log.info("  - SensorReadings.csv: %.2f MB", sensor_size / (1024 * 1024))
    log.info("  - SafetyIncidents.csv: %.2f KB", incidents_size / 1024)
    
    return True


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------
def generate_history(args: argparse.Namespace) -> bool:
    """Execute generate_history.py with configured parameters."""
    log.info("=" * 80)
    log.info("STEP 1: Generating Historical Data")
    log.info("=" * 80)
    log.info("Days:     %d", args.days)
    log.info("Interval: %d seconds", args.interval)
    log.info("Output:   %s", HISTORY_DATA_DIR)
    log.info("=" * 80)
    
    cmd = [
        sys.executable,
        str(GENERATE_SCRIPT),
        "--days", str(args.days),
        "--interval", str(args.interval),
        "--output-dir", str(HISTORY_DATA_DIR),
    ]
    
    log.info("Running: %s", " ".join(cmd))
    
    try:
        result = subprocess.run(
            cmd,
            check=True,
            capture_output=False,  # Stream output to console
            text=True,
        )
        log.info("✓ Historical data generation completed successfully")
        return True
    except subprocess.CalledProcessError as e:
        log.error("✗ Historical data generation failed with exit code %d", e.returncode)
        return False
    except FileNotFoundError:
        log.error("✗ Python interpreter or script not found")
        return False
    except Exception as e:
        log.error("✗ Unexpected error during generation: %s", e)
        return False


# ---------------------------------------------------------------------------
# Ingestion
# ---------------------------------------------------------------------------
def ingest_csv(args: argparse.Namespace, csv_path: Path, table_name: str) -> bool:
    """Execute ingest_history.py for a single CSV file."""
    log.info("  Ingesting %s → %s.%s…", csv_path.name, args.database, table_name)
    
    cmd = [
        sys.executable,
        str(INGEST_SCRIPT),
        "--csv", str(csv_path),
        "--cluster", args.cluster,
        "--database", args.database,
        "--table", table_name,
    ]
    
    # Add authentication parameters if provided
    if args.tenant_id:
        cmd.extend(["--tenant-id", args.tenant_id])
    if args.client_id:
        cmd.extend(["--client-id", args.client_id])
    if args.client_secret:
        cmd.extend(["--client-secret", args.client_secret])
    
    # Add dry-run flag if specified
    if args.dry_run:
        cmd.append("--dry-run")
    
    log.debug("Running: %s", " ".join(cmd))
    
    try:
        result = subprocess.run(
            cmd,
            check=True,
            capture_output=False,
            text=True,
        )
        log.info("  ✓ %s ingestion completed", csv_path.name)
        return True
    except subprocess.CalledProcessError as e:
        log.error("  ✗ %s ingestion failed with exit code %d", csv_path.name, e.returncode)
        return False
    except Exception as e:
        log.error("  ✗ Unexpected error during ingestion of %s: %s", csv_path.name, e)
        return False


def ingest_history(args: argparse.Namespace) -> bool:
    """Execute ingestion for both SensorReadings and SafetyIncidents."""
    log.info("=" * 80)
    log.info("STEP 2: Ingesting Historical Data")
    log.info("=" * 80)
    log.info("Cluster:  %s", args.cluster)
    log.info("Database: %s", args.database)
    log.info("Dry Run:  %s", args.dry_run)
    log.info("=" * 80)
    
    # Ingest SensorReadings
    sensor_success = ingest_csv(args, SENSOR_CSV, "SensorReadings")
    
    # Ingest SafetyIncidents
    incidents_success = ingest_csv(args, INCIDENTS_CSV, "SafetyIncidents")
    
    if sensor_success and incidents_success:
        log.info("✓ All ingestions completed successfully")
        return True
    elif sensor_success or incidents_success:
        log.warning("⚠ Partial success: some ingestions failed")
        return False
    else:
        log.error("✗ All ingestions failed")
        return False


# ---------------------------------------------------------------------------
# Main Pipeline
# ---------------------------------------------------------------------------
def run_pipeline(args: argparse.Namespace) -> int:
    """Execute the full historical data pipeline."""
    log.info("")
    log.info("=" * 80)
    log.info("HISTORICAL DATA PIPELINE — Mining RTI Demo")
    log.info("=" * 80)
    log.info("Mode:     %s", 
             "DRY RUN (no ingestion)" if args.dry_run else
             "GENERATE ONLY" if args.skip_ingest else
             "INGEST ONLY" if args.skip_generate else
             "FULL PIPELINE")
    log.info("=" * 80)
    log.info("")
    
    start_time = time.time()
    
    # Step 1: Generate historical data (unless skipped)
    if not args.skip_generate:
        generation_ok = generate_history(args)
        if not generation_ok:
            log.error("Pipeline failed at generation stage")
            return 2  # Exit code 2: generation failure
        log.info("")
    else:
        log.info("=" * 80)
        log.info("STEP 1: Generation (SKIPPED)")
        log.info("=" * 80)
        log.info("Using existing CSV files at: %s", HISTORY_DATA_DIR)
        log.info("")
    
    # Validate generated files exist
    if not validate_generated_files():
        log.error("CSV validation failed — cannot proceed with ingestion")
        return 1  # Exit code 1: configuration error
    
    # Step 2: Ingest data (unless skipped)
    if not args.skip_ingest:
        ingestion_ok = ingest_history(args)
        
        elapsed = time.time() - start_time
        log.info("")
        log.info("=" * 80)
        log.info("PIPELINE COMPLETE")
        log.info("=" * 80)
        log.info("Status:   %s", "SUCCESS ✓" if ingestion_ok else "FAILED ✗")
        log.info("Duration: %.1f seconds", elapsed)
        log.info("=" * 80)
        
        if args.dry_run:
            log.info("")
            log.info("NOTE: This was a DRY RUN. No data was actually ingested.")
            log.info("      Remove --dry-run flag to perform actual ingestion.")
        
        if not ingestion_ok:
            if not args.skip_generate:
                return 4  # Exit code 4: partial failure (generation succeeded, ingestion failed)
            else:
                return 3  # Exit code 3: ingestion failure
        
        return 0  # Success
    else:
        elapsed = time.time() - start_time
        log.info("")
        log.info("=" * 80)
        log.info("GENERATION COMPLETE (Ingestion skipped)")
        log.info("=" * 80)
        log.info("Duration: %.1f seconds", elapsed)
        log.info("CSV files ready at: %s", HISTORY_DATA_DIR)
        log.info("=" * 80)
        log.info("")
        log.info("To ingest the generated data later, run:")
        log.info("  python deploy_history.py --skip-generate --cluster <URI> --database <DB>")
        return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Automated pipeline: generate and ingest historical mining sensor data",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Full pipeline with defaults (30 days, 30-second intervals)
  python deploy_history.py \\
      --cluster https://cluster.kusto.fabric.microsoft.com \\
      --database MiningOps

  # Custom parameters
  python deploy_history.py \\
      --cluster https://cluster.kusto.fabric.microsoft.com \\
      --database MiningOps \\
      --days 7 \\
      --interval 60

  # CI/CD with service principal
  python deploy_history.py \\
      --cluster https://cluster.kusto.fabric.microsoft.com \\
      --database MiningOps \\
      --tenant-id $AZURE_TENANT_ID \\
      --client-id $AZURE_CLIENT_ID \\
      --client-secret $AZURE_CLIENT_SECRET

  # Dry run (validate config and generate data, but don't ingest)
  python deploy_history.py \\
      --cluster https://cluster.kusto.fabric.microsoft.com \\
      --database MiningOps \\
      --dry-run

  # Skip generation and ingest existing CSV
  python deploy_history.py \\
      --cluster https://cluster.kusto.fabric.microsoft.com \\
      --database MiningOps \\
      --skip-generate

  # Generate only (useful for testing data generation)
  python deploy_history.py \\
      --cluster https://cluster.kusto.fabric.microsoft.com \\
      --database MiningOps \\
      --skip-ingest

Credential Chain:
  1. CLI args (--tenant-id, --client-id, --client-secret)
  2. Environment variables (AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET)
  3. DefaultAzureCredential (Azure CLI, managed identity)
  4. Interactive browser (fallback)
        """,
    )
    
    # Generation parameters
    parser.add_argument(
        "--days",
        type=int,
        default=30,
        help="Number of days of historical data to generate (default: 30)",
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=30,
        help="Seconds between sensor readings (default: 30; use 60 for smaller files)",
    )
    
    # Ingestion parameters
    parser.add_argument(
        "--cluster",
        default=os.getenv("FABRIC_CLUSTER_URI"),
        help="Kusto cluster URI (e.g., https://cluster.kusto.fabric.microsoft.com). Env: FABRIC_CLUSTER_URI",
    )
    parser.add_argument(
        "--database",
        default=os.getenv("FABRIC_DATABASE", "MiningOps"),
        help="KQL database name (default: MiningOps). Env: FABRIC_DATABASE",
    )
    
    # Authentication parameters
    parser.add_argument(
        "--tenant-id",
        default=os.getenv("AZURE_TENANT_ID"),
        help="Azure AD tenant ID (for service principal auth). Env: AZURE_TENANT_ID",
    )
    parser.add_argument(
        "--client-id",
        default=os.getenv("AZURE_CLIENT_ID"),
        help="Azure AD client ID (for service principal auth). Env: AZURE_CLIENT_ID",
    )
    parser.add_argument(
        "--client-secret",
        default=os.getenv("AZURE_CLIENT_SECRET"),
        help="Azure AD client secret (for service principal auth). Env: AZURE_CLIENT_SECRET",
    )
    
    # Pipeline control flags
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Generate data and validate configuration, but do not ingest",
    )
    parser.add_argument(
        "--skip-generate",
        action="store_true",
        help="Skip data generation; ingest existing CSV files only",
    )
    parser.add_argument(
        "--skip-ingest",
        action="store_true",
        help="Generate data only; do not ingest (useful for testing generation)",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose debug logging",
    )
    
    args = parser.parse_args()
    
    # Validation
    if args.skip_generate and args.skip_ingest:
        parser.error("Cannot specify both --skip-generate and --skip-ingest (nothing to do)")
    
    if args.skip_generate and args.dry_run:
        parser.error("Cannot use --dry-run with --skip-generate (dry-run affects ingestion)")
    
    if not args.skip_ingest and not args.cluster:
        parser.error("--cluster is required for ingestion (or set FABRIC_CLUSTER_URI env var)")
    
    # Set logging level
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
    
    return args


def main() -> None:
    """Main entry point."""
    validate_environment()
    args = parse_args()
    
    try:
        exit_code = run_pipeline(args)
        sys.exit(exit_code)
    except KeyboardInterrupt:
        log.warning("\nPipeline interrupted by user")
        sys.exit(130)  # Standard exit code for SIGINT
    except Exception as e:
        log.error("Unexpected pipeline error: %s", e, exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
