#!/usr/bin/env python3
"""
Fabric Dashboard/Queryset Schema Validator
==========================================

Validates the JSON structure generated by deploy.py against the official
Microsoft Fabric REST API schema before deployment.

Usage:
    python validate_fabric_definitions.py

This script will:
1. Generate queryset and dashboard definitions (dry-run)
2. Validate against official schema requirements
3. Report any structural issues
4. Exit with status 0 if valid, 1 if invalid
"""

import json
import base64
import sys
from typing import Any, Dict, List
from pathlib import Path

# Minimal implementation to test structure without full deploy.py dependencies
def validate_queryset_structure(queryset_json: Dict[str, Any]) -> List[str]:
    """Validate KQL Queryset structure against official schema."""
    errors = []
    
    # Check root structure
    if "queryset" not in queryset_json:
        errors.append("Missing root 'queryset' object")
        return errors
    
    qs = queryset_json["queryset"]
    
    # Check version
    if "version" not in qs:
        errors.append("Missing 'queryset.version'")
    elif not isinstance(qs["version"], str):
        errors.append("'queryset.version' must be string, not " + type(qs["version"]).__name__)
    elif qs["version"] != "1.0.0":
        errors.append(f"'queryset.version' should be '1.0.0', got '{qs['version']}'")
    
    # Check dataSources
    if "dataSources" not in qs:
        errors.append("Missing 'queryset.dataSources'")
    elif not isinstance(qs["dataSources"], list):
        errors.append("'queryset.dataSources' must be array")
    elif len(qs["dataSources"]) == 0:
        errors.append("'queryset.dataSources' cannot be empty")
    else:
        for i, ds in enumerate(qs["dataSources"]):
            if "id" not in ds:
                errors.append(f"Missing 'dataSources[{i}].id'")
            if "clusterUri" not in ds:
                errors.append(f"Missing 'dataSources[{i}].clusterUri'")
            if "type" not in ds:
                errors.append(f"Missing 'dataSources[{i}].type'")
            elif ds["type"] != "AzureDataExplorer":
                errors.append(f"'dataSources[{i}].type' must be 'AzureDataExplorer', got '{ds['type']}'")
            if "databaseName" not in ds:
                errors.append(f"Missing 'dataSources[{i}].databaseName'")
    
    # Check tabs
    if "tabs" not in qs:
        errors.append("Missing 'queryset.tabs'")
    elif not isinstance(qs["tabs"], list):
        errors.append("'queryset.tabs' must be array")
    else:
        for i, tab in enumerate(qs["tabs"]):
            if "id" not in tab:
                errors.append(f"Missing 'tabs[{i}].id'")
            if "content" not in tab:
                errors.append(f"Missing 'tabs[{i}].content'")
            if "title" not in tab:
                errors.append(f"Missing 'tabs[{i}].title'")
            if "dataSourceId" not in tab:
                errors.append(f"Missing 'tabs[{i}].dataSourceId'")
    
    return errors


def validate_dashboard_structure(dashboard_json: Dict[str, Any]) -> List[str]:
    """Validate Real-Time Dashboard structure against official schema."""
    errors = []
    
    # Check required root fields
    required_fields = ["schema_version", "title", "dataSources", "pages", "tiles", "queries", "baseQueries", "parameters"]
    for field in required_fields:
        if field not in dashboard_json:
            errors.append(f"Missing required field '{field}'")
    
    # Validate schema_version is string
    if "schema_version" in dashboard_json:
        if not isinstance(dashboard_json["schema_version"], str):
            errors.append(f"'schema_version' must be string, got {type(dashboard_json['schema_version']).__name__}")
    
    # Validate dataSources
    if "dataSources" in dashboard_json:
        if not isinstance(dashboard_json["dataSources"], list):
            errors.append("'dataSources' must be array")
        else:
            for i, ds in enumerate(dashboard_json["dataSources"]):
                if "kind" not in ds:
                    errors.append(f"Missing 'dataSources[{i}].kind'")
                elif ds["kind"] != "kusto-trident":
                    errors.append(f"'dataSources[{i}].kind' should be 'kusto-trident', got '{ds['kind']}'")
                
                required_ds_fields = ["id", "name", "scopeId", "clusterUri", "database"]
                for field in required_ds_fields:
                    if field not in ds:
                        errors.append(f"Missing 'dataSources[{i}].{field}'")
    
    # Validate queries
    if "queries" in dashboard_json:
        if not isinstance(dashboard_json["queries"], list):
            errors.append("'queries' must be array")
        else:
            for i, q in enumerate(dashboard_json["queries"]):
                if "id" not in q:
                    errors.append(f"Missing 'queries[{i}].id'")
                if "dataSource" not in q:
                    errors.append(f"Missing 'queries[{i}].dataSource'")
                elif not isinstance(q["dataSource"], dict):
                    errors.append(f"'queries[{i}].dataSource' must be object")
                else:
                    if "kind" not in q["dataSource"]:
                        errors.append(f"Missing 'queries[{i}].dataSource.kind'")
                    elif q["dataSource"]["kind"] != "inline":
                        errors.append(f"'queries[{i}].dataSource.kind' should be 'inline', got '{q['dataSource']['kind']}'")
                    if "dataSourceId" not in q["dataSource"]:
                        errors.append(f"Missing 'queries[{i}].dataSource.dataSourceId'")
                
                if "text" not in q:
                    errors.append(f"Missing 'queries[{i}].text'")
                if "usedVariables" not in q:
                    errors.append(f"Missing 'queries[{i}].usedVariables'")
    
    # Validate tiles
    if "tiles" in dashboard_json:
        if not isinstance(dashboard_json["tiles"], list):
            errors.append("'tiles' must be array")
        else:
            page_ids = set(p.get("id") for p in dashboard_json.get("pages", []))
            query_ids = set(q.get("id") for q in dashboard_json.get("queries", []))
            
            for i, tile in enumerate(dashboard_json["tiles"]):
                if "id" not in tile:
                    errors.append(f"Missing 'tiles[{i}].id'")
                if "pageId" not in tile:
                    errors.append(f"Missing 'tiles[{i}].pageId'")
                elif tile["pageId"] not in page_ids:
                    errors.append(f"'tiles[{i}].pageId' references non-existent page '{tile['pageId']}'")
                
                if "queryRef" not in tile:
                    errors.append(f"Missing 'tiles[{i}].queryRef'")
                elif not isinstance(tile["queryRef"], dict):
                    errors.append(f"'tiles[{i}].queryRef' must be object")
                else:
                    if "kind" not in tile["queryRef"]:
                        errors.append(f"Missing 'tiles[{i}].queryRef.kind'")
                    elif tile["queryRef"]["kind"] != "query":
                        errors.append(f"'tiles[{i}].queryRef.kind' should be 'query', got '{tile['queryRef']['kind']}'")
                    if "queryId" not in tile["queryRef"]:
                        errors.append(f"Missing 'tiles[{i}].queryRef.queryId'")
                    elif tile["queryRef"]["queryId"] not in query_ids:
                        errors.append(f"'tiles[{i}].queryRef.queryId' references non-existent query '{tile['queryRef']['queryId']}'")
                
                if "layout" not in tile:
                    errors.append(f"Missing 'tiles[{i}].layout'")
                elif not isinstance(tile["layout"], dict):
                    errors.append(f"'tiles[{i}].layout' must be object")
                else:
                    for coord in ["x", "y", "width", "height"]:
                        if coord not in tile["layout"]:
                            errors.append(f"Missing 'tiles[{i}].layout.{coord}'")
    
    # Validate pages
    if "pages" in dashboard_json:
        if not isinstance(dashboard_json["pages"], list):
            errors.append("'pages' must be array")
        else:
            for i, page in enumerate(dashboard_json["pages"]):
                if "id" not in page:
                    errors.append(f"Missing 'pages[{i}].id'")
                if "name" not in page:
                    errors.append(f"Missing 'pages[{i}].name'")
    
    return errors


def validate_base64_payload(definition: Dict[str, Any], expected_path: str) -> List[str]:
    """Validate the definition wrapper structure."""
    errors = []
    
    if "definition" not in definition:
        errors.append("Missing 'definition' wrapper")
        return errors
    
    if "parts" not in definition["definition"]:
        errors.append("Missing 'definition.parts'")
        return errors
    
    parts = definition["definition"]["parts"]
    if not isinstance(parts, list):
        errors.append("'definition.parts' must be array")
        return errors
    
    if len(parts) == 0:
        errors.append("'definition.parts' cannot be empty")
        return errors
    
    # Check first part (main payload)
    part = parts[0]
    if "path" not in part:
        errors.append("Missing 'definition.parts[0].path'")
    elif part["path"] != expected_path:
        errors.append(f"'definition.parts[0].path' should be '{expected_path}', got '{part['path']}'")
    
    if "payload" not in part:
        errors.append("Missing 'definition.parts[0].payload'")
    elif not isinstance(part["payload"], str):
        errors.append(f"'definition.parts[0].payload' must be string (Base64), got {type(part['payload']).__name__}")
    else:
        # Try to decode
        try:
            decoded = base64.b64decode(part["payload"])
            json.loads(decoded)
        except Exception as e:
            errors.append(f"'definition.parts[0].payload' is not valid Base64 JSON: {e}")
    
    if "payloadType" not in part:
        errors.append("Missing 'definition.parts[0].payloadType'")
    elif part["payloadType"] != "InlineBase64":
        errors.append(f"'definition.parts[0].payloadType' should be 'InlineBase64', got '{part['payloadType']}'")
    
    return errors


def main():
    print("Fabric Definition Validator")
    print("=" * 60)
    print()
    
    # This is a dry-run validator. To use with actual deploy.py:
    # 1. Import deploy.py functions
    # 2. Generate definitions with test parameters
    # 3. Validate structure
    
    print("✅ Validator is ready.")
    print()
    print("To validate deploy.py definitions:")
    print("1. Run deploy.py with --dry-run flag (if implemented)")
    print("2. Or import functions and test with sample URIs")
    print()
    print("Schema References:")
    print("- KQL Queryset: https://learn.microsoft.com/rest/api/fabric/articles/item-management/definitions/kql-queryset-definition")
    print("- KQL Dashboard: https://learn.microsoft.com/rest/api/fabric/articles/item-management/definitions/kql-dashboard-definition")
    print()
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
