#!/usr/bin/env python3
"""
Fabric Dashboard/Queryset Schema Validator
==========================================

Validates the JSON structure generated by deploy.py against the official
Microsoft Fabric Git integration schema (v52).

Usage:
    python validate_fabric_definitions.py [--cluster-uri URI] [--database DB]

    With no arguments, runs against fake/stub values to verify structure only.
    Pass real cluster URI and database name to verify with production values.

This script will:
1. Generate queryset and dashboard definitions via deploy.py builders
2. Validate against official schema requirements
3. Report any structural issues
4. Exit with status 0 if valid, 1 if invalid

Schema references:
  KQL Queryset:  https://learn.microsoft.com/rest/api/fabric/articles/item-management/definitions/kql-queryset-definition
  KQL Dashboard: https://learn.microsoft.com/rest/api/fabric/articles/item-management/definitions/kql-dashboard-definition
"""

import argparse
import json
import base64
import sys
import uuid
from typing import Any, Dict, List
from pathlib import Path

# Minimal implementation to test structure without full deploy.py dependencies
def validate_queryset_structure(queryset_json: Dict[str, Any]) -> List[str]:
    """Validate KQL Queryset structure against official schema.

    Per official docs, the RealTimeQueryset.json payload has root fields
    version/dataSources/tabs with NO outer "queryset" wrapper key.
    """
    errors = []

    # Root fields are version/dataSources/tabs — no outer "queryset" wrapper.
    qs = queryset_json

    # Check version
    if "version" not in qs:
        errors.append("Missing root 'version'")
    elif not isinstance(qs["version"], str):
        errors.append("'version' must be string, not " + type(qs["version"]).__name__)
    elif qs["version"] != "1.0.0":
        errors.append(f"'version' should be '1.0.0', got '{qs['version']}'")

    # Check dataSources
    if "dataSources" not in qs:
        errors.append("Missing 'dataSources'")
    elif not isinstance(qs["dataSources"], list):
        errors.append("'dataSources' must be array")
    elif len(qs["dataSources"]) == 0:
        errors.append("'dataSources' cannot be empty")
    else:
        for i, ds in enumerate(qs["dataSources"]):
            if "id" not in ds:
                errors.append(f"Missing 'dataSources[{i}].id'")
            if "clusterUri" not in ds:
                errors.append(f"Missing 'dataSources[{i}].clusterUri'")
            if "type" not in ds:
                errors.append(f"Missing 'dataSources[{i}].type'")
            elif ds["type"] != "AzureDataExplorer":
                errors.append(f"'dataSources[{i}].type' must be 'AzureDataExplorer', got '{ds['type']}'")
            if "databaseName" not in ds:
                errors.append(f"Missing 'dataSources[{i}].databaseName'")

    # Check tabs
    if "tabs" not in qs:
        errors.append("Missing 'tabs'")
    elif not isinstance(qs["tabs"], list):
        errors.append("'tabs' must be array")
    else:
        for i, tab in enumerate(qs["tabs"]):
            if "id" not in tab:
                errors.append(f"Missing 'tabs[{i}].id'")
            if "content" not in tab:
                errors.append(f"Missing 'tabs[{i}].content'")
            if "title" not in tab:
                errors.append(f"Missing 'tabs[{i}].title'")
            if "dataSourceId" not in tab:
                errors.append(f"Missing 'tabs[{i}].dataSourceId'")
    
    return errors


def validate_dashboard_structure(dashboard_json: Dict[str, Any]) -> List[str]:
    """Validate Real-Time Dashboard structure against official schema (Fabric RTD v52).

    Key v52 behaviours:
    - schema_version is an integer (52), not a string.
    - dataSources[i].kind must be "KQLDatabase" (Git integration schema).
    - queries[i] uses a flat "dataSourceId" field, not a nested "dataSource" object.
    - queryRef uses kind="query".
    """
    errors = []

    # Check required root fields
    required_fields = ["schema_version", "title", "dataSources", "pages", "tiles", "queries", "baseQueries", "parameters"]
    for field in required_fields:
        if field not in dashboard_json:
            errors.append(f"Missing required field '{field}'")

    # schema_version must be an integer (v52 uses integer, not string)
    if "schema_version" in dashboard_json:
        if not isinstance(dashboard_json["schema_version"], int):
            errors.append(f"'schema_version' must be int, got {type(dashboard_json['schema_version']).__name__}")

    # Validate dataSources
    if "dataSources" in dashboard_json:
        if not isinstance(dashboard_json["dataSources"], list):
            errors.append("'dataSources' must be array")
        else:
            for i, ds in enumerate(dashboard_json["dataSources"]):
                if "kind" not in ds:
                    errors.append(f"Missing 'dataSources[{i}].kind'")
                elif ds["kind"] != "KQLDatabase":
                    # Fabric Git integration schema v52 requires "KQLDatabase".
                    # "kusto-trident" was the legacy REST API value — no longer correct.
                    errors.append(f"'dataSources[{i}].kind' should be 'KQLDatabase', got '{ds['kind']}'")

                required_ds_fields = ["id", "name", "scopeId", "clusterUri", "database"]
                for field in required_ds_fields:
                    if field not in ds:
                        errors.append(f"Missing 'dataSources[{i}].{field}'")

    # Validate queries — v52 uses flat "dataSourceId", NOT a nested "dataSource" object
    if "queries" in dashboard_json:
        if not isinstance(dashboard_json["queries"], list):
            errors.append("'queries' must be array")
        else:
            for i, q in enumerate(dashboard_json["queries"]):
                if "id" not in q:
                    errors.append(f"Missing 'queries[{i}].id'")
                if "dataSourceId" not in q:
                    errors.append(f"Missing 'queries[{i}].dataSourceId'")
                if "text" not in q:
                    errors.append(f"Missing 'queries[{i}].text'")
                if "usedVariables" not in q:
                    errors.append(f"Missing 'queries[{i}].usedVariables'")
    
    # Validate tiles
    if "tiles" in dashboard_json:
        if not isinstance(dashboard_json["tiles"], list):
            errors.append("'tiles' must be array")
        else:
            page_ids = set(p.get("id") for p in dashboard_json.get("pages", []))
            query_ids = set(q.get("id") for q in dashboard_json.get("queries", []))
            
            for i, tile in enumerate(dashboard_json["tiles"]):
                if "id" not in tile:
                    errors.append(f"Missing 'tiles[{i}].id'")
                if "pageId" not in tile:
                    errors.append(f"Missing 'tiles[{i}].pageId'")
                elif tile["pageId"] not in page_ids:
                    errors.append(f"'tiles[{i}].pageId' references non-existent page '{tile['pageId']}'")
                
                if "queryRef" not in tile:
                    errors.append(f"Missing 'tiles[{i}].queryRef'")
                elif not isinstance(tile["queryRef"], dict):
                    errors.append(f"'tiles[{i}].queryRef' must be object")
                else:
                    if "kind" not in tile["queryRef"]:
                        errors.append(f"Missing 'tiles[{i}].queryRef.kind'")
                    elif tile["queryRef"]["kind"] != "query":
                        errors.append(f"'tiles[{i}].queryRef.kind' should be 'query', got '{tile['queryRef']['kind']}'")
                    if "queryId" not in tile["queryRef"]:
                        errors.append(f"Missing 'tiles[{i}].queryRef.queryId'")
                    elif tile["queryRef"]["queryId"] not in query_ids:
                        errors.append(f"'tiles[{i}].queryRef.queryId' references non-existent query '{tile['queryRef']['queryId']}'")
                
                if "layout" not in tile:
                    errors.append(f"Missing 'tiles[{i}].layout'")
                elif not isinstance(tile["layout"], dict):
                    errors.append(f"'tiles[{i}].layout' must be object")
                else:
                    for coord in ["x", "y", "width", "height"]:
                        if coord not in tile["layout"]:
                            errors.append(f"Missing 'tiles[{i}].layout.{coord}'")
    
    # Validate pages
    if "pages" in dashboard_json:
        if not isinstance(dashboard_json["pages"], list):
            errors.append("'pages' must be array")
        else:
            for i, page in enumerate(dashboard_json["pages"]):
                if "id" not in page:
                    errors.append(f"Missing 'pages[{i}].id'")
                if "name" not in page:
                    errors.append(f"Missing 'pages[{i}].name'")
    
    return errors


def validate_base64_payload(definition: Dict[str, Any], expected_path: str) -> List[str]:
    """Validate the definition wrapper structure."""
    errors = []
    
    if "definition" not in definition:
        errors.append("Missing 'definition' wrapper")
        return errors
    
    if "parts" not in definition["definition"]:
        errors.append("Missing 'definition.parts'")
        return errors
    
    parts = definition["definition"]["parts"]
    if not isinstance(parts, list):
        errors.append("'definition.parts' must be array")
        return errors
    
    if len(parts) == 0:
        errors.append("'definition.parts' cannot be empty")
        return errors
    
    # Check first part (main payload)
    part = parts[0]
    if "path" not in part:
        errors.append("Missing 'definition.parts[0].path'")
    elif part["path"] != expected_path:
        errors.append(f"'definition.parts[0].path' should be '{expected_path}', got '{part['path']}'")
    
    if "payload" not in part:
        errors.append("Missing 'definition.parts[0].payload'")
    elif not isinstance(part["payload"], str):
        errors.append(f"'definition.parts[0].payload' must be string (Base64), got {type(part['payload']).__name__}")
    else:
        # Try to decode
        try:
            decoded = base64.b64decode(part["payload"])
            json.loads(decoded)
        except Exception as e:
            errors.append(f"'definition.parts[0].payload' is not valid Base64 JSON: {e}")
    
    if "payloadType" not in part:
        errors.append("Missing 'definition.parts[0].payloadType'")
    elif part["payloadType"] != "InlineBase64":
        errors.append(f"'definition.parts[0].payloadType' should be 'InlineBase64', got '{part['payloadType']}'")
    
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate Fabric Dashboard/Queryset definitions")
    parser.add_argument("--cluster-uri", default="https://trd-fake.z11.kusto.fabric.microsoft.com",
                        help="KQL cluster URI (fake stub used if not provided)")
    parser.add_argument("--database", default="MiningOps",
                        help="Database name")
    parser.add_argument("--database-id", default=None,
                        help="Database UUID (random stub used if not provided)")
    args = parser.parse_args()

    database_id = args.database_id or str(uuid.uuid4())

    # Import deploy.py builders — resolve path relative to this file's repo root.
    repo_root = Path(__file__).resolve().parents[3]  # .squad/agents/lambert/ -> repo root
    sys.path.insert(0, str(repo_root))
    try:
        from deploy import build_queryset_definition, build_dashboard_definition
    except ImportError as exc:
        print(f"ERROR: Cannot import deploy.py from {repo_root}: {exc}", file=sys.stderr)
        return 1

    all_errors: list[str] = []

    print("Fabric Definition Validator")
    print("=" * 60)
    print(f"Cluster URI : {args.cluster_uri}")
    print(f"Database    : {args.database}")
    print(f"Database ID : {database_id}")
    print()

    # ── Queryset ──────────────────────────────────────────────────────────
    print("─── KQL Queryset ───")
    try:
        qs_def = build_queryset_definition(args.cluster_uri, args.database)
        qs_wrapper_errors = validate_base64_payload(qs_def, "RealTimeQueryset.json")
        if qs_wrapper_errors:
            for e in qs_wrapper_errors:
                print(f"  ❌ WRAPPER: {e}")
            all_errors.extend(qs_wrapper_errors)
        else:
            qs_json = json.loads(base64.b64decode(qs_def["definition"]["parts"][0]["payload"]))
            qs_body_errors = validate_queryset_structure(qs_json)
            if qs_body_errors:
                for e in qs_body_errors:
                    print(f"  ❌ SCHEMA: {e}")
                all_errors.extend(qs_body_errors)
            else:
                tab_count = len(qs_json.get("tabs", []))
                print(f"  ✅ Schema valid ({tab_count} query tabs)")
    except Exception as exc:
        msg = f"Queryset build failed: {exc}"
        print(f"  ❌ BUILD ERROR: {msg}")
        all_errors.append(msg)

    print()

    # ── Dashboard ─────────────────────────────────────────────────────────
    print("─── Real-Time Dashboard ───")
    try:
        db_def = build_dashboard_definition(args.cluster_uri, args.database, database_id)
        db_wrapper_errors = validate_base64_payload(db_def, "RealTimeDashboard.json")
        if db_wrapper_errors:
            for e in db_wrapper_errors:
                print(f"  ❌ WRAPPER: {e}")
            all_errors.extend(db_wrapper_errors)
        else:
            db_json = json.loads(base64.b64decode(db_def["definition"]["parts"][0]["payload"]))
            db_body_errors = validate_dashboard_structure(db_json)
            if db_body_errors:
                for e in db_body_errors:
                    print(f"  ❌ SCHEMA: {e}")
                all_errors.extend(db_body_errors)
            else:
                tile_count = len(db_json.get("tiles", []))
                page_count = len(db_json.get("pages", []))
                print(f"  ✅ Schema valid ({tile_count} tiles across {page_count} pages)")
    except Exception as exc:
        msg = f"Dashboard build failed: {exc}"
        print(f"  ❌ BUILD ERROR: {msg}")
        all_errors.append(msg)

    print()
    print("=" * 60)
    if all_errors:
        print(f"RESULT: ❌ FAILED — {len(all_errors)} error(s) found")
        return 1
    else:
        print("RESULT: ✅ PASSED — all definitions comply with schema")
        return 0


if __name__ == "__main__":
    sys.exit(main())
